
export function openInStackBlitz(htmlCode: string) {
  // Create a form to submit to StackBlitz API
  const form = document.createElement('form');
  form.method = 'POST';
  form.target = '_blank';
  form.action = 'https://stackblitz.com/run';
  
  // Project definition
  const fileField = document.createElement('input');
  fileField.type = 'hidden';
  fileField.name = 'project[files][index.html]';
  fileField.value = htmlCode;
  form.appendChild(fileField);

  const templateField = document.createElement('input');
  templateField.type = 'hidden';
  templateField.name = 'project[template]';
  templateField.value = 'html';
  form.appendChild(templateField);
  
  const titleField = document.createElement('input');
  titleField.type = 'hidden';
  titleField.name = 'project[title]';
  titleField.value = 'Pic2Code Export';
  form.appendChild(titleField);

  const descField = document.createElement('input');
  descField.type = 'hidden';
  descField.name = 'project[description]';
  descField.value = 'Generated by Pic2Code';
  form.appendChild(descField);

  document.body.appendChild(form);
  form.submit();
  document.body.removeChild(form);
}