


import JSZip from 'jszip';

export const generateProjectZip = async (
  htmlCode: string, 
  reactCode: string | null, 
  flutterCode: string | null,
  reactNativeExpoCode: string | null,
  reactNativeCliCode: string | null,
  colors: string[] = []
) => {
  const zip = new JSZip();

  // 1. Basic HTML Version
  const htmlFolder = zip.folder("html-version");
  if (htmlFolder) {
    htmlFolder.file("index.html", htmlCode);
    htmlFolder.file("README.md", `# HTML Version\n\nOpen \`index.html\` in your browser to view the project.\n\nStyled with Tailwind CSS via CDN.`);
  }

  // 2. React Version (if available)
  if (reactCode) {
    const reactFolder = zip.folder("react-version");
    if (reactFolder) {
      reactFolder.file("App.tsx", reactCode);
      
      const packageJson = {
        name: "pic-2-code-react",
        version: "1.0.0",
        private: true,
        dependencies: {
          "react": "^18.2.0",
          "react-dom": "^18.2.0",
          "lucide-react": "^0.294.0",
          "clsx": "^2.0.0",
          "tailwind-merge": "^2.0.0"
        },
        scripts: {
          "start": "react-scripts start",
          "build": "react-scripts build"
        }
      };
      
      reactFolder.file("package.json", JSON.stringify(packageJson, null, 2));

      // Generate tailwind.config.js
      const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        ${colors.map((c, i) => `'custom-${i + 1}': '${c}',`).join('\n        ')}
      }
    },
  },
  plugins: [],
}`;
      reactFolder.file("tailwind.config.js", tailwindConfig);

      reactFolder.file("README.md", `# React Version\n\n1. Run \`npm install\`\n2. Run \`npm start\`\n\nGenerated by Pic2Code.`);
    }
  }

  // 3. Flutter Version (if available)
  if (flutterCode) {
    const flutterFolder = zip.folder("flutter-version");
    if (flutterFolder) {
      const libFolder = flutterFolder.folder("lib");
      libFolder?.file("main.dart", flutterCode);

      const pubspec = `name: pic2code_flutter
description: A new Flutter project generated by Pic2Code.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
`;
      flutterFolder.file("pubspec.yaml", pubspec);
      flutterFolder.file("README.md", `# Flutter Version\n\n1. Ensure you have Flutter installed.\n2. Run \`flutter pub get\`\n3. Run \`flutter run\`\n\nGenerated by Pic2Code.`);
    }
  }

  // 4. React Native Expo Version (if available)
  if (reactNativeExpoCode) {
    const rnFolder = zip.folder("react-native-expo-version");
    if (rnFolder) {
      rnFolder.file("App.tsx", reactNativeExpoCode);

      const packageJson = {
        name: "pic-2-code-react-native-expo",
        version: "1.0.0",
        main: "node_modules/expo/AppEntry.js",
        scripts: {
          "start": "expo start",
          "android": "expo start --android",
          "ios": "expo start --ios",
          "web": "expo start --web"
        },
        dependencies: {
          "expo": "~50.0.0",
          "expo-status-bar": "~1.11.1",
          "react": "18.2.0",
          "react-native": "0.73.0",
          "lucide-react-native": "^0.4.0"
        },
        devDependencies: {
          "@babel/core": "^7.20.0",
          "@types/react": "~18.2.45",
          "typescript": "^5.1.3"
        }
      };

      rnFolder.file("package.json", JSON.stringify(packageJson, null, 2));
      rnFolder.file("README.md", `# React Native (Expo) Version\n\n1. Run \`npm install\`\n2. Run \`npm start\`\n\nGenerated by Pic2Code.`);
    }
  }

  // 5. React Native CLI Version (if available)
  if (reactNativeCliCode) {
    const rnCliFolder = zip.folder("react-native-cli-version");
    if (rnCliFolder) {
      rnCliFolder.file("App.tsx", reactNativeCliCode);

      const packageJson = {
        name: "pic-2-code-react-native-cli",
        version: "1.0.0",
        scripts: {
          "start": "react-native start",
          "android": "react-native run-android",
          "ios": "react-native run-ios"
        },
        dependencies: {
          "react": "18.2.0",
          "react-native": "0.73.0",
          "lucide-react-native": "^0.4.0",
          "react-native-svg": "^14.1.0"
        },
        devDependencies: {
          "@babel/core": "^7.20.0",
          "@types/react": "~18.2.45",
          "typescript": "^5.1.3"
        }
      };

      rnCliFolder.file("package.json", JSON.stringify(packageJson, null, 2));
      rnCliFolder.file("README.md", `# React Native (CLI) Version\n\n1. Initialize a new project: \`npx react-native init MyProject\`\n2. Install dependencies: \`npm install lucide-react-native react-native-svg\`\n3. Replace \`App.tsx\` with this file.\n4. Run \`npm run android\` or \`npm run ios\`\n\nGenerated by Pic2Code.`);
    }
  }

  const content = await zip.generateAsync({ type: "blob" });
  
  // Trigger download
  const url = URL.createObjectURL(content);
  const a = document.createElement('a');
  a.href = url;
  a.download = "pic-2-code-project.zip";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};